### ISSUE TITLE
Create 2D platform level Design in unity 

### ISSUE THREAD

**Issue by m0hit-kumar** [Developer-Student-Clubs-MMDU/Game-Development#2]
- Use free assets only
- Can create own asset if required

**Comment by ShivamKr9304** [comment]
we have create a design only in this issue
&
what are minimum requirement for this issue

**Comment by m0hit-kumar** [comment]
> we have create a design only in this issue & what are minimum requirement for this issue

use free assests only and make a intresting 2D map thats all, you can take reference of games of diffrent 2D games available out there in the market

**Comment by ShivamKr9304** [comment]
can you assign me this

**Comment by m0hit-kumar** [comment]
> can you assign me this

ok go head with this
