### ISSUE TITLE
Create free roam city map 2D/3D

### ISSUE THREAD

**Issue by m0hit-kumar** [Developer-Student-Clubs-MMDU/Game-Development#3]

**Comment by ShivamKr9304** [comment]
what are the requirements for this issue

**Comment by m0hit-kumar** [comment]
> what are the requirements for this issue

you have to make a city roam map without the player, you can use any city for reference and can use free assets available.

**Comment by ShivamKr9304** [comment]
can you assign me plz

**Comment by m0hit-kumar** [comment]
> can you assign me plz

go ahead start contributing

**Comment by ShivamKr9304** [comment]
plz accept my first pull request to make my second pull second request
