### ISSUE TITLE
Create a 3D Avatar in Blender

### ISSUE THREAD

**Issue by m0hit-kumar** [Developer-Student-Clubs-MMDU/Game-Development#4]

**Comment by m0hit-kumar** [comment]
> I am interested in this work. Please assign it to me.

ok let me know what are you planning for the avatar

**Comment by MrJayendra** [comment]
What type of Avatar do you want ?

**Comment by m0hit-kumar** [comment]
> What type of Avatar do you want?

Do you want inspiration? We want anything that is unique from already existing characters like we have in Valorant we have different characters or something unique like that. if want inspiration I can send you a pic.  Mohit kumar#1046 this is my discord contact me there

**Comment by ShivamKr9304** [comment]
can you asign me this

**Comment by m0hit-kumar** [comment]
> can you asign me this

you can start working on it
